/**
 * seed.js — populates the reference data required by the application:
 * the 22 Major Arcana cards, the four spreads, and the positions
 * belonging to each spread.
 *
 * Reference data is fixed application data rather than user data, so it
 * is inserted once at setup rather than created at runtime.
 *
 * Usage: node db/seed.js  (run after init.js)
 */
const path = require('path');
const Database = require('better-sqlite3');

// cards.js was written for the browser and attaches its data to `window`,
// which does not exist in Node. A minimal stand-in allows the existing
// file to be reused as the single source of truth for the card data.
global.window = {};
require(path.join(__dirname, '..', 'public', 'js', 'cards.js'));

const { cards, spreads } = global.window.Arcana;

const db = new Database(path.join(__dirname, 'arcana.db'));

// Statements are prepared once and executed repeatedly, so the query is
// parsed and planned a single time rather than on every insertion.
//
// The placeholders (?) keep values separate from the statement itself:
// the structure is fixed during parsing, before any value is bound, so
// supplied data cannot alter the command (OWASP, 2025h).
const insertCard = db.prepare(
  'INSERT INTO cards (number, name, meaning) VALUES (?, ?, ?)'
);

const insertSpread = db.prepare(
  'INSERT INTO spreads (code, name, description, combined_text) VALUES (?, ?, ?, ?)'
);

const insertPosition = db.prepare(
  'INSERT INTO positions (spread_id, position_index, name) VALUES (?, ?, ?)'
);

// Spreads and their positions are written across two tables, so the
// insertions are wrapped in a single transaction. Either every row is
// committed or none is, preventing a spread from being stored without
// the positions that give it meaning (Haerder and Reuter, 1983).
const seedDatabase = db.transaction(() => {
  cards.forEach((card) => {
    insertCard.run(card.number, card.name, card.meaning);
  });

  // `spreads` is keyed by code ('one', 'three'...), so each entry yields
  // both the key and its object; the key is stored as the `code` column.
  Object.entries(spreads).forEach(([code, spread]) => {
    const result = insertSpread.run(
      code,
      spread.name,
      spread.description,
      spread.combined
    );

    // The identifier is generated by the database, so it is read back
    // and used as the foreign key on the dependent position rows.
    const spreadId = result.lastInsertRowid;

    // In cards.js the positions are an array nested inside the spread,
    // a repeating group that breaches first normal form. Each element
    // becomes its own row here, with its order preserved in the index.
    spread.positions.forEach((positionName, index) => {
      insertPosition.run(spreadId, index, positionName);
    });
  });
});

seedDatabase();

// Row counts confirm the insertion; the table name is a fixed internal
// value, as placeholders can bind values but not identifiers.
const countOf = (table) =>
  db.prepare(`SELECT COUNT(*) AS total FROM ${table}`).get().total;

console.log('Reference data inserted:\n');
console.log(`  cards:     ${countOf('cards')}`);
console.log(`  spreads:   ${countOf('spreads')}`);
console.log(`  positions: ${countOf('positions')}`);

db.close();